name: lgpdjus
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.3+49

environment:
  sdk: '>=2.16.0 <3.0.0'

publish_to: none

dependencies:
  logging: ^1.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^2.0.1
  cpfcnpj:
    git:
      url: https://github.com/erickhaendel/dart-cpfcnpj.git
      ref: "6258774d3de58ee9122f2b6047ebb0c5b833df19"
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  connectivity_plus: "^1.0.3"
  device_info: ^2.0.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_analytics: ^10.0.3
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  flutter_mobx: ^2.0.0
  flutter_modular: 3.3.1
  flutter_svg: ^0.22.0
  flutter_tags: ^1.0.0-nullsafety.1
  flutter_widget_from_html: ^0.6.1
  freezed_annotation: ^0.14.2
  mask_text_input_formatter: ^2.0.0
  mobx: ^2.0.1
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  timeago: ^3.1.0
  url_launcher: ^6.1.6
  uuid: ^3.0.4
  webview_flutter: ^2.0.8
  google_fonts: ^2.1.0
  rxdart: ^0.26.0
  asuka: ^2.0.0-nullsafety.2
  stack_trace: ^1.10.0
  progress_state_button: ^1.0.3
  rounded_loading_button: ^2.0.5
  camera: ^0.10.0+3
  async: ^2.6.1
  cross_file: ^0.3.1+1
  flutter_custom_tabs: ^1.0.4
  flutter_web_auth: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: "cd516a8e7483bfc7971ec9ac8f2d589e68247441"
  freezed: ^0.14.2
  mobx_codegen: ^2.0.1+3
  mockito: ^5.0.10

flutter_icons:
  ios: true
  android: true
  image_path_android: 'assets/images/icon/android.png'
  image_path_ios: 'assets/images/icon/ios.png'

flutter_launcher_name:
  name: 'LGPDjus'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/rubik/
    - assets/images/svg/drawer/account_setting.svg
    - assets/images/svg/drawer/trash.svg
    - assets/images/svg/drawer/user_profile.svg
    - assets/images/svg/bottom_bar/compose_tweet.svg
    - assets/images/svg/bottom_bar/compose_tweet_selected.svg
    - assets/images/svg/bottom_bar/emergency_controll.svg
    - assets/images/svg/bottom_bar/feed.svg
    - assets/images/svg/bottom_bar/feed_selected.svg
    - assets/images/svg/bottom_bar/bell.svg
    - assets/images/svg/bottom_bar/board.svg
    - assets/images/svg/bottom_bar/notification.svg
    - assets/images/svg/reset_password/recovery_password_step_1.svg
    - assets/images/svg/reset_password/recovery_password_step_2.svg
    - assets/images/svg/reset_password/recovery_password_step_3.svg
    - assets/images/svg/placeholder.svg
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/svg/appbar/lgpdjus.svg
    - assets/images/notification.svg
    - assets/images/svg/registration/done.svg
    - assets/images/tutorial/
    - assets/images/svg/ticket/warning_rounded.svg

    # Account
    - assets/images/svg/profile/edit.svg
    # Menu
    - assets/images/svg/drawer/info.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/rubik/Rubik-LightItalic.ttf
          style: italic
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
  icon: flutter pub run flutter_launcher_icons:main
  name: flutter pub run flutter_launcher_name:main
