#!/bin/bash

set -e

PROJECT_DIR=$(dirname $(dirname `realpath ${BASH_SOURCE[0]}`))

cd $PROJECT_DIR

bundle exec fastlane android distribute_android_beta --verbose
bundle exec fastlane ios testflight_distribute --verbose
